spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://120.27.232.182:5432/ow   #172.16.139.165(aliyun)
    url: jdbc:postgresql://172.16.63.36:1990/ow
    username: root
    password: "@root8*8*"
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,logback
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true